package(default_visibility = ["//visibility:public"])

load("@io_bazel_rules_closure//closure:defs.bzl", "closure_js_template_library")

closure_js_template_library(
    name = "soy",
    srcs = [
        "ui.soy",
    ],
    visibility = ["//visibility:public"],
)
